version: "3.3"
services:
  db:
    image:  "postgres:13"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
  web:
    image: my-node-todo:1.5
    ports:
      - '8080:5000'
    depends_on:
        - db
    links:
        - db
    environment:
        - PGHOST=db
        - PGUSER=local
        - PGDATABASE=postgres
        - PGPASSWORD=12345
        - PGPORT=5433
      
volumes:
    pg-data: 
