version: "3.3"
services:
  web:
    build: .
    ports: 
      - "8080:5000"
  db:
    image:  "postgres:13"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres

volumes:
  pgdata: